version: '2' 
services:
    db:
      image: postgres
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=circuit

    circuit:
      image: circuit
      ports:
        - 3000:3000
