version: '2' 
services:
    loadbalancer:
      image: jasonwyatt/nginx-loadbalancer
      environment:
        - CIRCUIT_PATH=/
        - CIRCUIT_1_PORT_3000_TCP_ADDR=circuit_0
        - CIRCUIT_2_PORT_3000_TCP_ADDR=circuit_1
        - CIRCUIT_3_PORT_3000_TCP_ADDR=circuit_2
        - CIRCUIT_REMOTE_PORT=3000
      ports:
        - 80:80

    db:
      image: postgres
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=circuit
        - PGDATA=/var/lib/postgresql/data/pgdata
      volumes:
       - db-volume:/var/lib/postgresql/data

    circuit_0:
      image: circuit
      ports:
        - 3000:3000
    circuit_1:
      image: circuit
      ports:
        - 3001:3000
    circuit_2:
      image: circuit
      ports:
        - 3002:3000

volumes:
    db-volume:
