apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: circuit

spec:
  replicas: 3
  template:
    metadata:
      name: circuit
      labels:
        app: circuit
    spec:
      containers:
        - name: circuit
          image: eu.gcr.io/circuit-yesod/circuit
