execution:
- concurrency: 1
  scenario: CircuitBidAnon
  
scenarios:
  CircuitBidAnon:
    default-address: http://127.0.0.1
    retrieve-resources: true
    requests:
      - auth/login

reporting:
- module: final-stats
- module: console

settings:
  check-interval: 5s
  default-executor: jmeter

provisioning: local
